// Auto-generated by scripts/process-images.mjs. Do not edit directly.

export interface GeneratedMediaDimensions {
  width: number;
  height: number;
  blurDataURL: string;
}

export const GENERATED_MEDIA: Record<string, GeneratedMediaDimensions> = {};
