import fs from "fs";
import path from "path";
import sharp from "sharp";

const SOURCE_DIR = path.join(process.cwd(), "public", "images", "source");
const OUTPUT_DIR = path.join(process.cwd(), "public", "images");
const GENERATED_FILE = path.join(process.cwd(), "src", "lib", "media.generated.ts");

const WIDTHS = [480, 768, 1200, 1920];

async function ensureDirs() {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
}

function getAllSourceFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(getAllSourceFiles(fullPath));
    } else if (/\.(jpg|jpeg|png|webp)$/i.test(entry.name)) {
      files.push({ path: fullPath, filename: entry.name });
    }
  }
  return files;
}

async function processImages() {
  await ensureDirs();

  const allSourceFiles = getAllSourceFiles(SOURCE_DIR);
  const generatedMediaMap = {};

  for (const fileObj of allSourceFiles) {
    const nameWithoutExt = path.parse(fileObj.filename).name.toLowerCase().replace(/[^a-z0-9_-]/g, "-");
    const image = sharp(fileObj.path);
    const metadata = await image.metadata();

    const origWidth = metadata.width || 1200;
    const origHeight = metadata.height || 800;

    // Generate 16px base64 blur placeholder (stripping EXIF by default)
    const blurBuffer = await sharp(fileObj.path)
      .resize(16)
      .toBuffer();
    const blurDataURL = `data:image/${metadata.format || "jpeg"};base64,${blurBuffer.toString("base64")}`;

    // Process output sizes & strip EXIF/GPS metadata (sharp strips metadata by default when converting)
    for (const width of WIDTHS) {
      if (width > origWidth) continue;

      const resizedImage = sharp(fileObj.path).resize(width);

      // AVIF
      const avifPath = path.join(OUTPUT_DIR, `${nameWithoutExt}-${width}.avif`);
      if (!fs.existsSync(avifPath) || fs.statSync(fileObj.path).mtime > fs.statSync(avifPath).mtime) {
        await resizedImage.clone().avif({ quality: 55 }).toFile(avifPath);
      }

      // WebP
      const webpPath = path.join(OUTPUT_DIR, `${nameWithoutExt}-${width}.webp`);
      if (!fs.existsSync(webpPath) || fs.statSync(fileObj.path).mtime > fs.statSync(webpPath).mtime) {
        await resizedImage.clone().webp({ quality: 72 }).toFile(webpPath);
      }

      // JPEG
      const jpgPath = path.join(OUTPUT_DIR, `${nameWithoutExt}-${width}.jpg`);
      if (!fs.existsSync(jpgPath) || fs.statSync(fileObj.path).mtime > fs.statSync(jpgPath).mtime) {
        await resizedImage.clone().jpeg({ quality: 80 }).toFile(jpgPath);
      }
    }

    generatedMediaMap[nameWithoutExt] = {
      width: origWidth,
      height: origHeight,
      blurDataURL,
    };
  }

  const generatedContent = `// Auto-generated by scripts/process-images.mjs. Do not edit directly.

export interface GeneratedMediaDimensions {
  width: number;
  height: number;
  blurDataURL: string;
}

export const GENERATED_MEDIA: Record<string, GeneratedMediaDimensions> = ${JSON.stringify(generatedMediaMap, null, 2)};
`;

  fs.writeFileSync(GENERATED_FILE, generatedContent, "utf-8");
  console.log(`Successfully processed ${allSourceFiles.length} image(s). Generated metadata in src/lib/media.generated.ts`);
}

processImages().catch((err) => {
  console.error("Error processing images:", err);
  process.exit(1);
});
